import { Equip, onceMap } from './type';
let magicStone = new onceMap;
let t;
t = new Equip;
t.name = '奔涌之息宝石';
t.data.push({ type: '攻击强化', value: 3354, times: 1 });
t.tag = ['CD'];
t.other = ['CDR+50%'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '未知文明-星石';
t.data.push({ type: '攻击强化', value: 3988, times: 1 });
t.tag = ['被击转化'];
t.other = ['恢复hp'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '子夜的圣域';
t.data.push({ type: '攻击强化', value: 4528, times: 1 });
t.tag = ['CD'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '未知的黄金石碑';
t.data.push({ type: '攻击强化', value: 3720, times: 1 });
t.tag = ['特效'];
t.other = ['异抗+15%'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '和平捍卫者';
t.data.push({ type: '攻击强化', value: 4258, times: 1 });
t.tag = ['所有速度', '出血'];
t.other = ['恢复hp', '加速'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '逆流之魂灵珠';
t.data.push({ type: '攻击强化', value: 4528, times: 1 });
t.data.push({ type: '攻击强化', value: 2075, times: 1 });
t.tag = ['宠物数量', 'CD', '所有速度'];
t.other = ['CD-8%'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '炙热之情宝石';
t.data.push({ type: '攻击强化', value: 4796, times: 1 });
t.tag = ['睡眠', '睡眠时间', '睡眠抗性'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '虚伪之石';
t.data.push({ type: '攻击强化', value: 3180, times: 1 });
t.tag = ['附魔翻倍'];
t.other = ['附魔翻倍'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '吞噬黑暗的心脏';
t.data.push({ type: '攻击强化', value: 4796, times: 1 });
t.tag = ['所有速度'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '不败奖牌';
t.data.push({ type: '攻击强化', value: 3988, times: 1 });
t.tag = ['被击转化'];
t.other = ['恢复hp'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '迷你电池包';
t.data.push({ type: '攻击强化', value: 5066, times: 1 });
t.data.push({ type: '攻击强化', value: 504, times: 5 });
t.data.push({ type: '攻击强化', value: 2223, times: 0 });
t.tag = ['mp套', 'mp消耗量增加'];
t.other = ['mp消耗量增加'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '自然灵息露珠';
t.data.push({ type: '攻击强化', value: 3988, times: 1 });
t.tag = ['被击转化'];
t.other = ['恢复hp'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '生机盎然的绿宝石';
t.data.push({ type: '攻击强化', value: 3988, times: 1 });
t.tag = ['被击转化'];
t.other = ['恢复hp'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '多德卡全息图';
t.data.push({ type: '攻击强化', value: 5240, times: 1 });
t.data.push({ type: '攻击强化', value: 3853, times: 1 });
t.other = ['眩晕时,CDR+20%'];
t.tag = ['CD', '自身眩晕'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '诅咒之心';
t.data.push({ type: '攻击强化', value: 3180, times: 1 });
t.data.push({ type: '技能攻击力', value: 15, times: 1 });
t.tag = ['破招伤害'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '猎龙者之证-龙心加工石';
t.data.push({ type: '攻击强化', value: 4796, times: 1 });
t.tag = ['技能等级', '属强'];
t.other = ['lv70技能等级提升', '属强+20'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '陆战型:战术车轮无人机';
t.data.push({ type: '攻击强化', value: 5066, times: 1 });
t.data.push({ type: '技能攻击力', value: 2, times: 5 });
t.tag = ['近战', '加速'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '静谧之像';
t.data.push({ type: '攻击强化', value: 4676, times: 1 });
for (let i = 0; i < 10; i++) {
    t.data.push({ type: '技能攻击力', value: 3, times: 1 });
}
t.tag = ['小技能特化', '小技能CD', '霸体'];
t.other = ['lv15-35技能CDR+10%'];
magicStone.set(t.name, t);
t = new Equip;
t.name = '灵动的慧眼';
t.data.push({ type: '攻击强化', value: 4796, times: 1 });
t.data.push({ type: '攻击强化', value: 667, times: 4 });
t.tag = ['所有速度'];
magicStone.set(t.name, t);
for (const v of magicStone.values()) {
    v.slot = '右槽';
    if (!v.isMyth) {
        v.data.push({
            type: '技能攻击力',
            value: 12,
            times: 1
        });
    }
}
export default magicStone;
