import { Equip, onceMap } from './type.js';
let necklace = new onceMap;
let t;
t = new Equip;
t.name = '第一个黑桃-贵族';
t.data.push({ type: '攻击强化', value: 3180, times: 1 });
t.tag = ['附魔翻倍'];
t.other = ['附魔翻倍'];
necklace.set(t.name, t);
t = new Equip;
t.name = '生命的脉动';
t.data.push({ type: '攻击强化', value: 3180, times: 1 });
t.tag = ['光强', '光属性自击'];
t.other = ['光强+30'];
necklace.set(t.name, t);
t = new Equip;
t.name = '黯星项链';
t.data.push({ type: '攻击强化', value: 4702, times: 1 });
t.data.push({ type: '攻击强化', value: 2668, times: 1 });
t.data.push({ type: '技能攻击力', value: 5, times: 1 });
t.tag = ['低血', '所有速度'];
t.other = ['属强+15'];
necklace.set(t.name, t);
t = new Equip;
t.name = '风化的恶意';
t.data.push({ type: '攻击强化', value: 3180, times: 1 });
t.tag = ['暗强', '暗属性自击'];
t.other = ['暗强+30'];
necklace.set(t.name, t);
t = new Equip;
t.name = '领域之心项链';
t.data.push({ type: '攻击强化', value: 5416, times: 1 });
t.data.push({ type: '攻击强化', value: 222, times: 20 });
t.data.push({ type: '技能攻击力', value: 3, times: 1 });
t.tag = ['金币数量'];
t.other = ['属强+15'];
necklace.set(t.name, t);
t = new Equip;
t.name = '战士的荣耀项链';
t.data.push({ type: '攻击强化', value: 3450, times: 1 });
t.tag = ['灼烧', '特效'];
t.other = ['火强+15', '攻击灼烧敌人时,剩余CD-0.5%'];
necklace.set(t.name, t);
t = new Equip;
t.name = '高科技闪影项链';
t.data.push({ type: '攻击强化', value: 4876, times: 1 });
t.data.push({ type: '技能攻击力', value: 10, times: 1 });
t.tag = ['手搓', 'CD'];
t.other = ['属强+15', '手搓非快捷栏技能时,CD-15%'];
necklace.set(t.name, t);
t = new Equip;
t.name = '五感之灵项链';
t.data.push({ type: '攻击强化', value: 4796, times: 1 });
t.tag = ['特效'];
t.other = ['施放悦翔后霸体30s', '跳跃力增加'];
necklace.set(t.name, t);
t = new Equip;
t.name = '浮光跃金项链';
t.data.push({ type: '攻击强化', value: 3450, times: 1 });
t.data.push({ type: '技能攻击力', value: 10, times: 1 });
t.tag = ['破招'];
necklace.set(t.name, t);
t = new Equip;
t.name = '守护龙的庇护-勇气';
t.data.push({ type: '攻击强化', value: 4796, times: 1 });
t.tag = ['技能等级'];
t.other = ['lv40技能等级上升', '属强+20'];
necklace.set(t.name, t);
t = new Equip;
t.name = '脉冲触发器';
t.data.push({ type: '攻击强化', value: 4796, times: 1 });
t.data.push({ type: '攻击强化', value: 2964, times: 1 });
t.tag = ['近战', '攻击速度'];
necklace.set(t.name, t);
t = new Equip;
t.name = '石巨人之心项链';
t.data.push({ type: '攻击强化', value: 3180, times: 1 });
t.tag = ['冰强', '冰属性自击'];
t.other = ['冰强+30'];
necklace.set(t.name, t);
t = new Equip;
t.name = '无尽的愤怒项链';
t.data.push({ type: '攻击强化', value: 5240, times: 1 });
t.data.push({ type: '技能攻击力', value: 8.64, times: 1 });
t.tag = ['无视防御'];
t.other = ['属强+15'];
necklace.set(t.name, t);
t = new Equip;
t.name = '残忍之心项链';
t.data.push({ type: '攻击强化', value: 3180, times: 1 });
t.tag = ['火强', '火属性自击'];
t.other = ['火强+30'];
necklace.set(t.name, t);
t = new Equip;
t.name = '熔丝项链';
t.data.push({ type: '攻击强化', value: 3720, times: 1 });
t.data.push({ type: '技能攻击力', value: 5, times: 1 });
t.tag = ['弱点'];
t.other = ['更变弱点属性'];
necklace.set(t.name, t);
t = new Equip;
t.name = '蓝色自然的种子';
t.data.push({ type: '攻击强化', value: 3720, times: 1 });
t.tag = ['灼烧', '灼烧伤害'];
t.other = ['冰强+15', '灼烧解冰时,灼烧伤害+30%'];
necklace.set(t.name, t);
t = new Equip;
t.name = '遥感之心项链';
t.data.push({ type: '攻击强化', value: 5510, times: 1 });
t.tag = ['恢复mp', 'mp消耗量增加'];
t.other = ['属强+15'];
necklace.set(t.name, t);
t = new Equip;
t.name = '骑士的赎罪';
t.data.push({ type: '攻击强化', value: 4528, times: 1 });
t.tag = ['所有速度', '前冲'];
necklace.set(t.name, t);
t = new Equip;
t.name = '温柔的旋律';
t.data.push({ type: '攻击强化', value: 4258, times: 1 });
t.tag = ['无敌', '睡眠'];
t.other = ['睡眠时进入无敌状态'];
necklace.set(t.name, t);
for (const v of necklace.values()) {
    v.slot = '项链';
    if (!v.isMyth) {
        v.data.push({
            type: '技能攻击力',
            value: 12,
            times: 1
        });
    }
}
export default necklace;
