import { Equip, onceMap, dataWords } from "./type.js";
let belts = new onceMap;
let t;
t = new Equip;
t.name = '自定义装备';
for (const word of dataWords) {
    t.data.push({ type: word, value: 0, times: 1 });
    t.data.push({ type: word, value: 0, times: 1 });
}
belts.set(t.name, t);
t = new Equip;
t.name = '御雷腰带';
t.data.push({ type: '攻击强化', value: 4523, times: 1 });
t.data.push({ type: '攻击强化', value: 356, times: 1 });
t.data.push({ type: '光强', value: +15, times: 1 });
t.tag = ['感电', '光强'];
belts.set(t.name, t);
t = new Equip;
t.name = '龙食腐者';
t.data.push({ type: '攻击强化', value: 3720, times: 1 });
t.data.push({ type: '冰强', value: +20, times: 1 });
t.tag = ['冰强', '冰抗'];
belts.set(t.name, t);
t = new Equip;
t.name = '动力之渊腰带';
t.data.push({ type: '攻击强化', value: 4258, times: 1 });
t.data.push({ type: '技能攻击力', value: 20, times: 1 });
t.tag = ['猴戏', '特化'];
belts.set(t.name, t);
t = new Equip;
t.name = '玉化亡灵腰甲';
t.data.push({ type: '攻击强化', value: 3450, times: 1 });
t.tag = ['召唤', '特效'];
belts.set(t.name, t);
t = new Equip;
t.name = '应尽之责腰带';
t.data.push({ type: '攻击强化', value: 2642, times: 1 });
t.data.push({ type: '技能攻击力', value: 14, times: 1 });
t.tag = ['手搓', '特化'];
t.data.push({ type: '属强', value: +20, times: 1 });
belts.set(t.name, t);
t = new Equip;
t.name = '静谧的星光腰带';
t.data.push({ type: '攻击强化', value: 4528, times: 1 });
t.data.push({ type: '攻击强化', value: 445, times: 5 });
t.tag = ['减伤', '角色状态'];
belts.set(t.name, t);
t = new Equip;
t.name = '信念之喘息腰带';
t.data.push({ type: '攻击强化', value: 4528, times: 1 });
t.data.push({ type: '攻击强化', value: 326, times: 10 });
t.data.push({ type: '攻击强化', value: 356, times: 1 });
t.tag = ['自身出血'];
belts.set(t.name, t);
t = new Equip;
t.name = '骄傲的意志腰带';
t.data.push({ type: '攻击强化', value: 4796, times: 1 });
t.data.push({ type: '攻击强化', value: 356, times: 1 });
t.tag = ['感电伤害', '感电'];
t.data.push({ type: '感电伤害', value: +15, times: 1 });
belts.set(t.name, t);
t = new Equip;
t.name = '纯粹的自然秩序';
t.data.push({ type: '攻击强化', value: 5066, times: 1 });
t.data.push({ type: '攻击强化', value: 356, times: 1 });
t.tag = ['特效', '感电'];
t.data.push({ type: '光强', value: +15, times: 1 });
belts.set(t.name, t);
t = new Equip;
t.name = '高科技战术腰带';
t.data.push({ type: '攻击强化', value: 5066, times: 1 });
t.tag = ['保护罩', '减伤', '恢复hp'];
belts.set(t.name, t);
t = new Equip;
t.name = '月落星沉腰带';
t.data.push({ type: '攻击强化', value: 4702, times: 1 });
t.data.push({ type: '攻击强化', value: 385, times: 0 });
t.tag = ['石化'];
t.data.push({ type: '属强', value: +15, times: 1 });
belts.set(t.name, t);
t = new Equip;
t.name = '千丝萦绕腰带';
t.data.push({ type: '攻击强化', value: 4917, times: 1 });
t.data.push({ type: '技能攻击力', value: 20, times: 1 });
t.tag = ['无需无色技能'];
belts.set(t.name, t);
t = new Equip;
t.name = '音律的夙愿';
t.data.push({ type: '攻击强化', value: 5336, times: 1 });
t.tag = ['恢复hp'];
belts.set(t.name, t);
t = new Equip;
t.name = '亘古的悬空石腰带';
t.data.push({ type: '攻击强化', value: 4164, times: 1 });
t.data.push({ type: '攻击强化', value: 356, times: 1 });
t.tag = ['自身中毒', 'CD'];
t.other = ["CDR+25%(觉醒除外)"];
belts.set(t.name, t);
t = new Equip;
t.name = '星灭光离腰带';
t.data.push({ type: '攻击强化', value: 4258, times: 1 });
t.tag = ['所有速度', '火抗', 'CD'];
t.other = ["大量速度", "CDR+10%(觉醒除外)"];
belts.set(t.name, t);
t = new Equip;
t.name = '恐惧缠绕腰带';
t.data.push({ type: '攻击强化', value: 3720, times: 1 });
t.data.push({ type: '技能攻击力', value: 12, times: 1 });
t.data.push({ type: '技能攻击力', value: 20, times: 1 });
t.tag = ['无色技能'];
belts.set(t.name, t);
t = new Equip;
t.name = '白玉无邪腰带';
t.data.push({ type: '攻击强化', value: 4528, times: 1 });
t.tag = ['附魔翻倍'];
t.other = ["附魔翻倍"];
belts.set(t.name, t);
t = new Equip;
t.name = '大地之翼腰带';
t.data.push({ type: '攻击强化', value: 4528, times: 1 });
t.tag = ['减伤', '异抗'];
belts.set(t.name, t);
t = new Equip;
t.name = '天才技术大师的百宝腰带';
t.data.push({ type: '攻击强化', value: 4917, times: 1 });
t.data.push({ type: '攻击强化', value: 2223, times: 1 });
t.data.push({ type: '攻击强化', value: 889, times: 3 });
t.tag = ['回蓝', 'mp套'];
t.other = ["mp消耗量+100%"];
belts.set(t.name, t);
for (const v of belts.values()) {
    v.slot = '腰带';
    if (!v.isMyth) {
        v.data.push({
            value: 12,
            type: '技能攻击力',
            times: 1
        });
    }
}
export default belts;

