import { Equip, onceMap } from "./type.js";
let coats = new onceMap;
let t;
t = new Equip;
t.name = '自定义装备';
for (let i = 0; i < 5; i++) {
    t.attrs.push({ type: '攻击强化', value: 0, times: 1 });
}
coats.set(t.name, t);
t = new Equip;
t.name = '轰天裂地石甲';
t.attrs.push({ type: '攻击强化', value: 3988 + (1482 - 808) * 2, times: 1 });
t.attrs.push({ type: '攻击强化', value: 926, times: 4 });
t.tag = ['队员人数'];
coats.set(t.name, t);
t = new Equip;
t.name = '高贵的神意上衣';
t.attrs.push({ type: '攻击强化', value: 3988 + (2021 - 808) * 2, times: 1 });
t.tag = ['无敌'];
coats.set(t.name, t);
t = new Equip;
t.name = '双面星云皮大衣';
t.attrs.push({ type: '攻击强化', value: 4379 + (2290 - 1078) * 2, times: 1 });
t.attrs.push({ type: '攻击速度', value: 5, times: 1 });
t.attrs.push({ type: '施放速度', value: 7.5, times: 1 });
t.tag = ['复活', '恢复mp'];
coats.set(t.name, t);
t = new Equip;
t.name = '玉化亡灵胸甲 ';
t.attrs.push({ type: '攻击强化', value: 4528 + (1886 - 1078) * 2, times: 1 });
t.tag = ['特效'];
coats.set(t.name, t);
t = new Equip;
t.name = '百折不挠的梦想';
t.attrs.push({ type: '攻击强化', value: 5066 + (2290 - 1347) * 2, times: 1 });
t.tag = ['睡眠', '复活', '恢复hp'];
coats.set(t.name, t);
t = new Equip;
t.name = '冤魂的执念上衣';
t.attrs.push({ type: '攻击强化', value: 4258 + (1886 - 943) * 2, times: 1 });
t.tag = ['变小', '回避率', '恢复mp', '恢复hp'];
coats.set(t.name, t);
t = new Equip;
t.name = '高科技战术指挥上衣';
t.attrs.push({ type: '攻击强化', value: 3988 + (1482 - 1078) * 2, times: 1 });
t.attrs.push({ type: '属强', value: 30, times: 1 });
t.tag = ['属强', '瞬移'];
coats.set(t.name, t);
t = new Equip;
t.name = '暗影流光战袍';
t.attrs.push({ type: '攻击强化', value: 5336, times: 1 });
t.tag = ['恢复hp', '诅咒', 'CD'];
t.attrs.push({ type: '冷却恢复速度', value: +20, times: 1 });
t.attrs.push({ type: '攻击速度', value: 8, times: 1 });
t.attrs.push({ type: '施放速度', value: 12, times: 1 });
coats.set(t.name, t);
t = new Equip;
t.name = '死亡蚕食胸甲';
t.attrs.push({ type: '攻击强化', value: 4528, times: 1 });
t.attrs.push({ type: '攻击强化', value: 4446, times: 0 });
t.attrs.push({ type: '攻击速度', value: 5, times: 3 });
t.attrs.push({ type: '施放速度', value: 7.5, times: 3 });
t.tag = ['复活', '无色'];
coats.set(t.name, t);
t = new Equip;
t.name = '守护之王者铠甲';
t.attrs.push({ type: '攻击强化', value: 4647, times: 1 });
t.attrs.push({ type: '攻击强化', value: 445, times: 5 });
t.tag = ['护盾', '召唤', '恢复hp'];
coats.set(t.name, t);
t = new Equip;
t.name = '屠龙者';
t.attrs.push({ type: '攻击强化', value: 5066 + (1751 - 1347) * 2, times: 1 });
t.attrs.push({ type: '攻击强化', value: 1186, times: 1 });
t.attrs.push({ type: '属强', value: 15, times: 1 });
t.tag = ['全属性附魔'];
coats.set(t.name, t);
t = new Equip;
t.name = '白金流光夹克';
t.attrs.push({ type: '攻击强化', value: 4528, times: 1 });
t.tag = ['附魔翻倍'];
t.other = ["附魔翻倍"];
coats.set(t.name, t);
t = new Equip;
t.name = '御力装甲上衣';
t.attrs.push({ type: '攻击强化', value: 4796 + (1616 - 1212) * 2, times: 1 });
t.attrs.push({ type: '攻击强化', value: 356, times: 1 });
t.tag = ['灼烧伤害', '灼烧'];
t.attrs.push({ type: '灼烧伤害', value: +15, times: 1 });
coats.set(t.name, t);
t = new Equip;
t.name = '深渊之源上衣';
t.attrs.push({ type: '攻击强化', value: 5066 + (1616 - 1347) * 2, times: 1 });
t.tag = ['属性强化', '全属性附魔'];
t.other = ["对应属强-10", "全属性轮流附魔"];
coats.set(t.name, t);
t = new Equip;
t.name = '澎湃之心上衣';
t.attrs.push({ type: '攻击强化', value: 4379 + (1886 - 1078) * 2, times: 1 });
t.attrs.push({ type: '属强', value: 10, times: 1 });
t.tag = ['恢复hp', '复活'];
coats.set(t.name, t);
t = new Equip;
t.name = '天才技术大师的研究服上衣';
t.attrs.push({ type: '攻击强化', value: 4917, times: 1 });
t.tag = ['恢复hp', '特效', 'CD'];
t.attrs.push({ type: '冷却恢复速度', value: +20, times: 1 });
coats.set(t.name, t);
t = new Equip;
t.name = '极魂之驱上衣';
t.attrs.push({ type: '攻击强化', value: 3960 + (1347 - 943) * 2, times: 1 });
t.tag = ['变大', '霸体', '恢复mp', '恢复hp', '特效'];
coats.set(t.name, t);
t = new Equip;
t.name = '大地的馈赠上衣';
t.attrs.push({ type: '攻击强化', value: 5066 + (2021 - 1347) * 2, times: 1 });
t.attrs.push({ type: '技能攻击力', value: 2, times: 1 });
t.tag = ['特效', '火强'];
t.attrs.push({ type: '火强', value: +15, times: 1 });
t.attrs.push({ type: '攻击速度', value: 1, times: 10 });
t.attrs.push({ type: '施放速度', value: 1.5, times: 10 });
coats.set(t.name, t);
t = new Equip;
t.name = '古老的探险家大衣';
t.attrs.push({ type: '攻击强化', value: 3180, times: 1 });
t.tag = ['额外指令', '搬砖 '];
coats.set(t.name, t);
t = new Equip;
t.name = '混乱核心胸甲';
t.attrs.push({ type: '攻击强化', value: 5336, times: 1 });
t.attrs.push({ type: '出血伤害', value: 5, times: 1 });
t.attrs.push({ type: '中毒伤害', value: 5, times: 1 });
t.attrs.push({ type: '感电伤害', value: 5, times: 1 });
t.attrs.push({ type: '灼烧伤害', value: 5, times: 1 });
t.tag = ['召唤'];
t.other = ['召唤'];
coats.set(t.name, t);
t = new Equip;
t.name = '逆转命运';
t.isMyth = true;
t.attrs.push({ type: '技能攻击力', value: 35, times: 1 });
t.attrs.push({ type: '技能攻击力', value: 5, times: 1 });
t.attrs.push({ type: '攻击速度', value: 6, times: 1 });
t.attrs.push({ type: '移动速度', value: 6, times: 1 });
t.attrs.push({ type: '施放速度', value: 9, times: 1 });
t.tag = ['神话'];
coats.set(t.name, t);
for (const v of coats.values()) {
    v.slot = '上衣';
    if (!v.isMyth) {
        v.attrs.push({
            type: '技能攻击力',
            value: 12,
            times: 1
        });
    }
}
export default coats;

